# -*- coding: utf-8 -*-
"""Chanci_Python_Profile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z76HOQNT5SZyNYylO0EEosg1nmsICo_w
"""

## Contains a example to profile a function using cProfile

import cProfile

def leibniz(n):
  # Description: Leibniz Formula using For loop and (-1)**n
  sumSeries = 0  # Initialize Sum
  for i in range(n):  # Iterate from 0 to N
    sumSeries += (-1) ** i / (2*i + 1)  # Add new term
  return sumSeries

cProfile.run('leibniz(1000)')  # Profile function